apiVersion: "argoproj.io/v1alpha1"
kind: AppProject
metadata:
  name: base-applications
  namespace: cicd
spec:
  description: "Contain all Base services deployments"
  sourceRepos:
    - https://github.com/JPedro-loureiro/big-data-on-eks.git
    - https://charts.external-secrets.io
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true