FROM --platform=linux/amd64 apache/airflow:2.11.0

# [Start-providers]
RUN pip install apache-airflow-providers-trino
# [End-providers]

# [Start-python-libs]
# install dbt into a virtual environment
RUN python -m venv dbt_venv && source dbt_venv/bin/activate && \
    pip install --no-cache-dir dbt-trino && deactivate

# Install all other libs
COPY requirements.txt /
RUN pip install --no-cache-dir -r /requirements.txt
# [End-python-libs]