resources:
- deployment-opa.yaml
- service-opa.yaml
configMapGenerator:
- name: opa-policies
  files:
  - ./rego_rules/main.rego
  - ./rego_rules/filter.rego
  - ./rego_rules/mask.rego
  - ./rego_rules/impersonation.rego