apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-gen
  namespace: kafka
spec:

  # specify aws region (mandatory)
  region: us-east-1

---

# apiVersion: external-secrets.io/v1beta1
# kind: ClusterExternalSecret
# metadata:
#   name: ecr-secret
#   namespace: external-secrets
# spec:
#   externalSecretName: ecr-secret
#   namespaceSelectors:
#   - matchLabels:
#       kubernetes.io/metadata.name: kafka
#   externalSecretSpec:
#     refreshInterval: "1h"
#     target:
#       name: ecr-secret
#     dataFrom:
#     - sourceRef:
#         generatorRef:
#           apiVersion: generators.external-secrets.io/v1alpha1
#           kind: ECRAuthorizationToken
#           name: "ecr-gen"

apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: ecr-secret
  namespace: external-secrets
spec:
  externalSecretName: ecr-secret
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: kafka
  externalSecretSpec:
    refreshInterval: "1h"
    target:
      name: ecr-secret
      template:
        engineVersion: v2
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: |
            {"auths":{"{{ .proxy_endpoint }}":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ .username}}:{{ .password }}"}}}
    dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: "ecr-gen"