apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-test
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-manager
    kind: ClusterSecretStore
  target:
    name: eso-test
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          app: test
        namespace: cicd
  data:
    - secretKey: key_in_the_kubernetes_secret
      remoteRef:
        # AWS Secrets Manager secret's name
        key: eso-test