apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  labels:
    app: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
      name: opa
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa:0.68.0
        ports:
        - name: http
          containerPort: 8181
        args:
        - "run"
        - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
        - "--server"
        - "/policies"
        - "--log-level"
        - "debug"
        volumeMounts:
        # - readOnly: true
        #   mountPath: /policies
        #   name: example-policy
        # - readOnly: true
        #   mountPath: /policies
        #   name: filter-example-policy
        # - readOnly: true
        #   mountPath: /policies
        #   name: mask-example-policy
        - readOnly: true
          mountPath: /policies
          name: opa-policies
      volumes:
      # - name: example-policy
      #   configMap:
      #     name: example-policy
      # - name: filter-example-policy
      #   configMap:
      #     name: filter-example-policy
      # - name: mask-example-policy
      #   configMap:
      #     name: mask-example-policy
      - name: opa-policies
        configMap:
          name: opa-policies