datalake:
  target: oauth
  outputs:
    oauth:
      type: trino
      method: oauth_console
      host: trino.bigdataoneks.click
      database: objectstore
      schema: datalake_bronze
      port: 443