datalake:
  target: oauth
  outputs:
    oauth:
      type: trino
      method: password
      user: dbt_trino
      password: dbt_trino
      host: trino.bigdataoneks.click
      database: objectstore
      schema: datalake_bronze
      http_scheme: https
      port: 443