datalake:
  target: prod
  outputs:
    prod:
      type: trino
      method: ldap
      user: dbt_user
      password: dbt_user
      host: trino.bigdataoneks.click
      database: objectstore
      schema: ""
      http_scheme: https
      port: 443