datalake:
  target: dev
  outputs:
    dev:
      type: trino
      method: oauth_console
      host: https://trino.bigdataoneks.click
      database: objectstore
      schema: datalake_bronze
      port: 433