datalake:
  target: oauth
  outputs:
    oauth:
      type: trino
      method: ldap
      user: dbt_user
      password: dbt_user
      host: trino.bigdataoneks.click
      database: objectstore
      schema: datalake_bronze
      # http_scheme: https
      port: 443