apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: external-secrets-operator
  namespace: cicd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: base-applications
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - "Validate=false"
      - "CreateNamespace=true"
      - "PrunePropagationPolicy=foreground"
      - "PruneLast=true"
      # - "ServerSideApply=true"
    retry:
      limit: 3
      backoff:
        duration   : "5s"
        factor     : 2
        maxDuration: "1m"
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.10.4
    chart: external-secrets
    helm:
      version: v3
      values: |
        ${values}
  