apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: base-applications
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - "Validate=false"
      - "CreateNamespace=true"
      - "PrunePropagationPolicy=foreground"
      - "PruneLast=true"
      - "ServerSideApply=true"
    retry:
      limit: 3
      backoff:
        duration   : "5s"
        factor     : 2
        maxDuration: "1m"
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 75.7.0
    chart: kube-prometheus-stack
    helm:
      version: v3
      values: |
        ${values}
  