apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: superset
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: big-data
  destination:
    server: https://kubernetes.default.svc
    namespace: superset
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - "Validate=false"
      - "CreateNamespace=true"
      - "PrunePropagationPolicy=foreground"
      - "PruneLast=true"
      # - "ServerSideApply=true"
    retry:
      limit: 3
      backoff:
        duration   : "5s"
        factor     : 2
        maxDuration: "1m"
  source:
    repoURL: https://apache.github.io/superset
    targetRevision: 0.14.2
    chart: superset
    helm:
      version: v3
      values: |
        ${values}
  